name: myevent
description: AplicaciÃ³n integral para organizar, crear, vender y gestionar eventos
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Design
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  lottie: ^3.0.0
  flutter_svg: ^2.0.9
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^13.0.0
  
  # Network
  http: ^1.1.2
  dio: ^5.4.0
  
  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.5
  
  # Storage
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  
  # Permissions
  permission_handler: ^11.1.0
  
  # Notifications
  flutter_local_notifications: ^19.5.0
  
  # Date & Time
  intl: ^0.18.1
  
  # Image Picker
  image_picker: ^1.0.7
  
  # Location
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  url_launcher: ^6.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/animations/
    - Y2K Icon.json
  
